name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          echo -e "\e[34mInstalling dependencies...\e[0m"
          npm install

      - name: Run tests
        run: |
          echo -e "\e[32mRunning unit tests...\e[0m"
          npm run test

      # - name: Run E2E tests
      #   run: |
      #     echo -e "\e[32mRunning E2E tests...\e[0m"
      #     npm run test:e2e

      - name: Generate coverage report
        run: |
          echo -e "\e[33mGenerating coverage report...\e[0m"
          npm run test:cov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
